sonar.projectName=car-repair-production-service
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.cs

sonar.exclusions=**/bin/**,**/obj/**
sonar.coverage.exclusions=**/Program.cs
